// Catálogo de productos adicionales (placas, controles, botoneras, contactoras)
// Generado a partir de LISTA_DE_PRECIOS_MACLAR_NUEVA.xls — sin precio ni imagen (se agregan después).
const MACLAR_EXTRA_CATEGORIES = [
  { id: "placas-accesorios", label: "Placas y Accesorios" },
  { id: "controles-electronicos", label: "Controles Electrónicos" },
  { id: "botoneras", label: "Botoneras" },
  { id: "contactoras-lg", label: "Contactoras LG" },
  { id: "controles-electromecanicos", label: "Controles Electromecánicos" },
];

const MACLAR_PRODUCTOS_EXTRA = [
  { id: "placas-accesorios-1-coordinador", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "coordinador", group: null, image: null },
  { id: "placas-accesorios-2-interfaz-alfan", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "Interfaz alfan.", group: null, image: null },
  { id: "placas-accesorios-3-placa-cea-31", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "placa CEA 31", group: null, image: null },
  { id: "placas-accesorios-4-placa-cea-51-fa-duplex", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "placa CEA 51 FA DUPLEX", group: null, image: null },
  { id: "placas-accesorios-5-placa-cea-51-fa-simplex", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "placa CEA 51 FA SIMPLEX", group: null, image: null },
  { id: "placas-accesorios-6-placa-de-llamadas-exteriores", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "placa de llamadas exteriores", group: null, image: null },
  { id: "placas-accesorios-7-placa-mac-07-h-16p", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "placa MAC 07 h/16P", group: null, image: null },
  { id: "placas-accesorios-8-placa-mac-07-h-8p", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "placa MAC 07 h/8P", group: null, image: null },
  { id: "placas-accesorios-9-tarjeta-alfan-mac-07-azul", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta alfan. MAC 07 azul", group: null, image: null },
  { id: "placas-accesorios-10-tarjeta-alfan-mac-07-rojo", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta alfan. MAC 07 Rojo", group: null, image: null },
  { id: "placas-accesorios-11-tarjeta-alfanum-con-interfaz", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta alfanum con interfaz", group: null, image: null },
  { id: "placas-accesorios-12-tarjeta-de-indic-1-3h", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta de indic. 1\"3H", group: null, image: null },
  { id: "placas-accesorios-13-tarjeta-de-indic-2-3h", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta de indic. 2\"3H", group: null, image: null },
  { id: "placas-accesorios-14-tarjeta-de-indic-alfa-azul", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta de indic. Alfa azul", group: null, image: null },
  { id: "placas-accesorios-15-tarjeta-de-indic-alfa-rojo", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta de indic. Alfa rojo", group: null, image: null },
  { id: "placas-accesorios-16-tarjeta-de-indic-lcd", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta de indic. LCD", group: null, image: null },
  { id: "placas-accesorios-17-tarjeta-de-indicador-7-seg-para-tablero", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta de indicador 7 seg para tablero", group: null, image: null },
  { id: "placas-accesorios-18-tarjeta-de-indicador-alfanum", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "tarjeta de indicador alfanum", group: null, image: null },
  { id: "placas-accesorios-19-placa-cea-10", cat: "placas-accesorios", catLabel: "Placas y Accesorios", name: "placa CEA 10", group: null, image: null },
  { id: "controles-electronicos-1-hidraulico-arr-dir-2-cont-basico-sin-nad", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "HIDRAULICO ARR. DIR. (2 CONT) BASICO SIN NADA + DE 4 PAR", group: null, image: null },
  { id: "controles-electronicos-2-hidraulico-arr-dir-con-bateria-y-retorno", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "HIDRAULICO ARR. DIR. CON BATERIA Y RETORNO PISO ESTACION", group: null, image: null },
  { id: "controles-electronicos-3-hidraulico-arr-estrella-triang-3-cont-su", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "HIDRAULICO ARR. ESTRELLA TRIANG.(3 CONT)SUMAR 3 CONTACT +", group: null, image: null },
  { id: "controles-electronicos-4-mac-07-cd-hasta-16p-pta-man-con-acelerac", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "MAC 07 CD HASTA 16P PTA. MAN. CON ACELERACION 22 AMP", group: null, image: null },
  { id: "controles-electronicos-5-mac-07-cd-hasta-16p-pta-man-sin-acelerac", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "MAC 07 CD HASTA 16P PTA. MAN. SIN ACELERACION 22 AMP", group: null, image: null },
  { id: "controles-electronicos-6-mac-07-cd-hasta-16p-pta-man-con-acelerac", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "MAC 07 CD HASTA 16P PTA. MAN. CON ACELERACION 32 AMP", group: null, image: null },
  { id: "controles-electronicos-7-mac-07-cd-hasta-16p-pta-man-sin-acelerac", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "MAC 07 CD HASTA 16P PTA. MAN. SIN ACELERACION 32 AMP", group: null, image: null },
  { id: "controles-electronicos-8-cea-51-fb-cd-hasta-16p-pta-man-con-acel-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CEA 51 FB CD HASTA 16P PTA. MAN CON ACEL. 22 AMP + 24P VA PISO S.", group: null, image: null },
  { id: "controles-electronicos-9-cea-51-fb-cd-hasta-16p-pta-man-sin-acel-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CEA 51 FB CD HASTA 16P PTA. MAN SIN ACEL. 22 AMP + 24P VA PISO S.", group: null, image: null },
  { id: "controles-electronicos-10-cea-51-fb-cd-hasta-16p-pta-man-con-acel-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CEA 51 FB CD HASTA 16P PTA. MAN CON ACEL 32 AMP + 24P VA PISO S.", group: null, image: null },
  { id: "controles-electronicos-11-cea-51-fb-cd-hasta-16p-pta-man-sin-acel-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CEA 51 FB CD HASTA 16P PTA. MAN SIN ACEL.32 AMP + 24P VA PISO S.", group: null, image: null },
  { id: "controles-electronicos-12-adic-por-triplex", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ADIC. POR TRIPLEX", group: null, image: null },
  { id: "controles-electronicos-13-adic-por-puertas-automaticas-2-cont-9-am", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ADIC. POR PUERTAS AUTOMATICAS 2 CONT 9 AMP. OP 220 o TRIFASICO", group: null, image: null },
  { id: "controles-electronicos-14-piso-sup-cd-de-25-par", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "PISO SUP. CD + DE 25 PAR", group: null, image: null },
  { id: "controles-electronicos-15-piso-sup-cc-de-17-par", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "PISO SUP. CC + DE 17 PAR", group: null, image: null },
  { id: "controles-electronicos-16-contact-32-amp-hasta-10-hp-sumar-al-basi", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CONTACT. 32 AMP. HASTA 10 HP SUMAR AL BASICO CON 22 AMP", group: null, image: null },
  { id: "controles-electronicos-17-contact-40-amp-hasta-15-hp-sumar-al-basi", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CONTACT. 40 AMP. HASTA 15 HP SUMAR AL BASICO CON 22 AMP", group: null, image: null },
  { id: "controles-electronicos-18-contact-50-amp-de-15-hp-sumar-al-basico-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CONTACT. 50 AMP. + DE 15 HP SUMAR AL BASICO CON 22 AMP", group: null, image: null },
  { id: "controles-electronicos-19-contact-65-amp-de-15-hp-sumar-al-basico-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CONTACT. 65 AMP. + DE 15 HP SUMAR AL BASICO CON 22 AMP", group: null, image: null },
  { id: "controles-electronicos-20-contactoras-85-amp", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CONTACTORAS 85 AMP.", group: null, image: null },
  { id: "controles-electronicos-21-contactoras-100-amp", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "CONTACTORAS 100 AMP.", group: null, image: null },
  { id: "controles-electronicos-22-kit-de-luz-de-emergencia-en-los-hidr-no-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "KIT DE LUZ DE EMERGENCIA (en los hidr no se cobra xq tiene la bateria)", group: null, image: null },
  { id: "controles-electronicos-23-adic-por-guardamotor", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ADIC. POR GUARDAMOTOR", group: null, image: null },
  { id: "controles-electronicos-24-sintetizador-de-voz-colocado", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "SINTETIZADOR DE VOZ COLOCADO", group: null, image: null },
  { id: "controles-electronicos-25-maniobra-selectiva-de-apertura-de-pta-so", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "MANIOBRA SELECTIVA DE APERTURA DE PTA. SOLO CON 51FA", group: null, image: null },
  { id: "controles-electronicos-26-kit-cea-31-con-teclado-de-acceso", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "KIT CEA 31 CON TECLADO DE ACCESO", group: null, image: null },
  { id: "controles-electronicos-27-pre-apertura-de-puerta-solo-con-cea-51", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "PRE APERTURA DE PUERTA (SOLO CON CEA 51)", group: null, image: null },
  { id: "controles-electronicos-28-pre-apertura-de-puerta-solo-con-cea-51-a", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "PRE APERTURA DE PUERTA (SOLO CON CEA 51) ADIC.X PARADA", group: null, image: null },
  { id: "controles-electronicos-29-adic-por-imanes-en-1-velocidad-x-parada", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ADIC. POR IMANES EN 1 VELOCIDAD X PARADA", group: null, image: null },
  { id: "controles-electronicos-30-adic-por-indicador-en-todos-los-pisos-1-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ADIC. POR INDICADOR EN TODOS LOS PISOS 1 DIGITO", group: null, image: null },
  { id: "controles-electronicos-31-adic-por-indicador-en-todos-los-pisos-2-", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ADIC. POR INDICADOR EN TODOS LOS PISOS 2 DIGITOS", group: null, image: null },
  { id: "controles-electronicos-32-adicional-por-doble-pta-aut-4-cont-9-amp", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ADICIONAL POR DOBLE PTA AUT 4 CONT 9 AMP", group: null, image: null },
  { id: "controles-electronicos-33-op-fv-no-lleva-adicional-x-pta-aut", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "OP FV NO LLEVA ADICIONAL X PTA AUT", group: null, image: null },
  { id: "controles-electronicos-34-frecuencia-variable-lazo-abierto-sin-enc", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "FRECUENCIA VARIABLE LAZO ABIERTO SIN ENCODER HASTA 90 MTS", group: null, image: null },
  { id: "controles-electronicos-35-yaskawa-hasta-5-hp-v1000-18", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 5 HP V1000 18", group: null, image: null },
  { id: "controles-electronicos-36-yaskawa-hasta-10-hp-v1000-23", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 10 HP V1000 23", group: null, image: null },
  { id: "controles-electronicos-37-yaskawa-hasta-15-hp-v1000-31", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 15 HP V1000 31", group: null, image: null },
  { id: "controles-electronicos-38-yaskawa-hasta-20-hp-v1000-38", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 20 HP V1000 38", group: null, image: null },
  { id: "controles-electronicos-39-yaskawa-hasta-25-hp-l1000-39", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 25 HP L1000 39", group: null, image: null },
  { id: "controles-electronicos-40-encoder", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ENCODER", group: null, image: null },
  { id: "controles-electronicos-41-frecuencia-variable-lazo-cerrado-con-enc", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "FRECUENCIA VARIABLE LAZO CERRADO CON ENCODER + DE 90 MTS", group: null, image: null },
  { id: "controles-electronicos-42-yaskawa-hasta-10-hp-l1000-19-con-encoder", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 10 HP L1000 19 CON ENCODER", group: null, image: null },
  { id: "controles-electronicos-43-yaskawa-hasta-15-hp-l1000-23-con-encoder", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 15 HP L1000 23 CON ENCODER", group: null, image: null },
  { id: "controles-electronicos-44-yaskawa-hasta-20-hp-l1000-30-con-encoder", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 20 HP L1000 30 CON ENCODER", group: null, image: null },
  { id: "controles-electronicos-45-yaskawa-hasta-25-hp", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 25 HP", group: null, image: null },
  { id: "controles-electronicos-46-yaskawa-hasta-30-hp", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 30 HP", group: null, image: null },
  { id: "controles-electronicos-47-yaskawa-hasta-40-hp", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "YASKAWA HASTA 40 HP", group: null, image: null },
  { id: "controles-electronicos-48-encoder", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "ENCODER", group: null, image: null },
  { id: "controles-electronicos-49-placa-pgx3", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "PLACA PGX3", group: null, image: null },
  { id: "controles-electronicos-50-unidad-de-frenado", cat: "controles-electronicos", catLabel: "Controles Electrónicos", name: "UNIDAD DE FRENADO", group: null, image: null },
  { id: "botoneras-1-b-corta-basico-0-par-acero", cat: "botoneras", catLabel: "Botoneras", name: "B.CORTA BASICO 0 PAR. ACERO", group: null, image: null },
  { id: "botoneras-2-b-pa-o-basico-0-par-acero", cat: "botoneras", catLabel: "Botoneras", name: "B.PAÑO BASICO 0 PAR. ACERO", group: null, image: null },
  { id: "botoneras-3-adic-por-parada-boton-m-m-acero-con-brai", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR PARADA BOTON M.M. ACERO CON BRAILLE", group: null, image: null },
  { id: "botoneras-4-adic-por-parada-boton-redondo-braille", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR PARADA BOTON REDONDO BRAILLE", group: null, image: null },
  { id: "botoneras-5-adic-por-indicador-1", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR 1\"", group: null, image: null },
  { id: "botoneras-6-adic-por-indicador-2", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR 2\"", group: null, image: null },
  { id: "botoneras-7-adic-por-indicador-alfanumerico-sin-fuen", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR ALFANUMERICO (SIN FUENTE)", group: null, image: null },
  { id: "botoneras-8-fuente-para-indicador-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "FUENTE PARA INDICADOR ALFANUMERICO", group: null, image: null },
  { id: "botoneras-9-adic-por-indicador-alfanumerico-autonomo", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR ALFANUMERICO AUTONOMO (c/accesorios)", group: null, image: null },
  { id: "botoneras-10-adic-por-indicador-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR 3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-11-adic-por-indicador-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR 3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-12-adic-por-indicador-lcd-azul-chico-quantu", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR LCD AZUL CHICO QUANTUM", group: null, image: null },
  { id: "botoneras-13-adic-por-indicador-lcd-azul-grande-quant", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR LCD AZUL GRANDE QUANTUM", group: null, image: null },
  { id: "botoneras-14-adic-por-indicador-lcd-4-3-color", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR LCD 4,3\" COLOR", group: null, image: null },
  { id: "botoneras-15-adic-por-indicador-lcd-5-6-color", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR LCD 5,6\" COLOR", group: null, image: null },
  { id: "botoneras-16-adic-por-indicador-lcd-7-color", cat: "botoneras", catLabel: "Botoneras", name: "ADIC. POR INDICADOR LCD 7\" COLOR", group: null, image: null },
  { id: "botoneras-17-interfaz-lcd", cat: "botoneras", catLabel: "Botoneras", name: "INTERFAZ LCD", group: null, image: null },
  { id: "botoneras-18-boton-ap-y-cp-m-m", cat: "botoneras", catLabel: "Botoneras", name: "BOTON AP Y CP M.M.", group: null, image: null },
  { id: "botoneras-19-extractor-m-m", cat: "botoneras", catLabel: "Botoneras", name: "EXTRACTOR M.M.", group: null, image: null },
  { id: "botoneras-20-flechas-direccionales", cat: "botoneras", catLabel: "Botoneras", name: "FLECHAS DIRECCIONALES", group: null, image: null },
  { id: "botoneras-21-c-s-ascensorista-3-bot-1-llave", cat: "botoneras", catLabel: "Botoneras", name: "C/S ASCENSORISTA (3 BOT. + 1 LLAVE)", group: null, image: null },
  { id: "botoneras-22-servicio-independiente", cat: "botoneras", catLabel: "Botoneras", name: "SERVICIO INDEPENDIENTE", group: null, image: null },
  { id: "botoneras-23-servicio-de-incendio", cat: "botoneras", catLabel: "Botoneras", name: "SERVICIO DE INCENDIO", group: null, image: null },
  { id: "botoneras-24-nicho-para-telefono", cat: "botoneras", catLabel: "Botoneras", name: "NICHO PARA TELEFONO", group: null, image: null },
  { id: "botoneras-25-grabado-blasting", cat: "botoneras", catLabel: "Botoneras", name: "GRABADO BLASTING", group: null, image: null },
  { id: "botoneras-26-gong-con-fuente-y-parlante-para-cabina", cat: "botoneras", catLabel: "Botoneras", name: "GONG CON FUENTE Y PARLANTE PARA CABINA", group: null, image: null },
  { id: "botoneras-27-braille-por-parada", cat: "botoneras", catLabel: "Botoneras", name: "BRAILLE POR PARADA", group: null, image: null },
  { id: "botoneras-28-luz-de-emergencia", cat: "botoneras", catLabel: "Botoneras", name: "LUZ DE EMERGENCIA", group: null, image: null },
  { id: "botoneras-29-intercomunicador-commax-te-timbre-boton-", cat: "botoneras", catLabel: "Botoneras", name: "INTERCOMUNICADOR COMMAX (TE+TIMBRE+BOTON+COLOCACION)", group: null, image: null },
  { id: "botoneras-30-adicional-por-pa-o-si-trae-la-chapa", cat: "botoneras", catLabel: "Botoneras", name: "ADICIONAL POR PAÑO SI TRAE LA CHAPA", group: null, image: null },
  { id: "botoneras-31-acrilico-doble-grabado-cap-max", cat: "botoneras", catLabel: "Botoneras", name: "ACRILICO DOBLE GRABADO CAP. MAX.", group: null, image: null },
  { id: "botoneras-32-boton-sonoro-por-cada-8-paradas", cat: "botoneras", catLabel: "Botoneras", name: "BOTON SONORO POR CADA 8 PARADAS", group: null, image: null },
  { id: "botoneras-33-teclado-de-acceso", cat: "botoneras", catLabel: "Botoneras", name: "TECLADO DE ACCESO", group: null, image: null },
  { id: "botoneras-34-botonera-de-inspeccion", cat: "botoneras", catLabel: "Botoneras", name: "BOTONERA DE INSPECCION", group: null, image: null },
  { id: "botoneras-35-parlante", cat: "botoneras", catLabel: "Botoneras", name: "PARLANTE", group: null, image: null },
  { id: "botoneras-36-adicional-por-alfanumerico-azul-tarjeta-", cat: "botoneras", catLabel: "Botoneras", name: "ADICIONAL POR ALFANUMERICO AZUL (TARJETA ENTERA)", group: null, image: null },
  { id: "botoneras-37-adicional-por-tapa-y-caja-acero-inclinad", cat: "botoneras", catLabel: "Botoneras", name: "ADICIONAL POR TAPA Y CAJA ACERO INCLINADO", group: null, image: null },
  { id: "botoneras-38-telefono-manos-libres-surix", cat: "botoneras", catLabel: "Botoneras", name: "TELEFONO MANOS LIBRES (SURIX)", group: null, image: null },
  { id: "botoneras-39-adicional-por-led-azul-por-parada", cat: "botoneras", catLabel: "Botoneras", name: "ADICIONAL POR LED AZUL POR PARADA", group: null, image: null },
  { id: "botoneras-40-preparado-para-te-sigma", cat: "botoneras", catLabel: "Botoneras", name: "PREPARADO PARA TE (SIGMA)", group: null, image: null },
  { id: "botoneras-41-modulo-prohibido-fumar", cat: "botoneras", catLabel: "Botoneras", name: "MODULO PROHIBIDO FUMAR", group: null, image: null },
  { id: "botoneras-42-bronce-50-sobre-acero", cat: "botoneras", catLabel: "Botoneras", name: "BRONCE + 50% SOBRE ACERO", group: null, image: null },
  { id: "botoneras-43-adicinal-por-pulido-combinado", cat: "botoneras", catLabel: "Botoneras", name: "ADICINAL POR PULIDO COMBINADO", group: null, image: null },
  { id: "botoneras-44-adicional-por-golpe-de-pu-o", cat: "botoneras", catLabel: "Botoneras", name: "ADICIONAL POR GOLPE DE PUÑO", group: null, image: null },
  { id: "botoneras-45-botones-de-piso", cat: "botoneras", catLabel: "Botoneras", name: "BOTONES DE PISO", group: null, image: null },
  { id: "botoneras-46-boton-exterior-simple-de-acero-m-m-sin-c", cat: "botoneras", catLabel: "Botoneras", name: "BOTON EXTERIOR SIMPLE DE ACERO M.M. SIN CAJA", group: null, image: null },
  { id: "botoneras-47-boton-exterior-doble-de-acero-m-m-sin-ca", cat: "botoneras", catLabel: "Botoneras", name: "BOTON EXTERIOR DOBLE DE ACERO M.M. SIN CAJA", group: null, image: null },
  { id: "botoneras-48-boton-exterior-simple-de-acero-con-caja", cat: "botoneras", catLabel: "Botoneras", name: "BOTON EXTERIOR SIMPLE DE ACERO CON CAJA", group: null, image: null },
  { id: "botoneras-49-boton-exterior-doble-de-acero-con-caja", cat: "botoneras", catLabel: "Botoneras", name: "BOTON EXTERIOR DOBLE DE ACERO CON CAJA", group: null, image: null },
  { id: "botoneras-50-boton-sonoro-para-exterior-por-cada-bes", cat: "botoneras", catLabel: "Botoneras", name: "BOTON SONORO PARA EXTERIOR (POR CADA BES)", group: null, image: null },
  { id: "botoneras-51-indicadores", cat: "botoneras", catLabel: "Botoneras", name: "INDICADORES", group: null, image: null },
  { id: "botoneras-52-decodificador", cat: "botoneras", catLabel: "Botoneras", name: "DECODIFICADOR", group: null, image: null },
  { id: "botoneras-53-abertura-para-indicador", cat: "botoneras", catLabel: "Botoneras", name: "ABERTURA PARA INDICADOR", group: null, image: null },
  { id: "botoneras-54-ventana-de-indicador-con-boton-con-caja", cat: "botoneras", catLabel: "Botoneras", name: "VENTANA DE INDICADOR CON BOTON CON CAJA", group: null, image: null },
  { id: "botoneras-55-ventana-de-indicador-con-boton-sin-caja", cat: "botoneras", catLabel: "Botoneras", name: "VENTANA DE INDICADOR CON BOTON SIN CAJA", group: null, image: null },
  { id: "botoneras-56-adicional-por-gong-en-tapa-de-indicador", cat: "botoneras", catLabel: "Botoneras", name: "ADICIONAL POR GONG EN TAPA DE INDICADOR", group: null, image: null },
  { id: "botoneras-57-ventana-con-indicador-horizontal", cat: "botoneras", catLabel: "Botoneras", name: "VENTANA CON INDICADOR HORIZONTAL", group: null, image: null },
  { id: "botoneras-58-horizontal-o-vertical-1", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL 1\"", group: null, image: null },
  { id: "botoneras-59-horizontal-o-vertical-2", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL 2\"", group: null, image: null },
  { id: "botoneras-60-horizontal-o-vertical-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL 3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-61-horizontal-o-vertical-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL 3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-62-horizontal-o-vertical-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL ALFANUMERICO", group: null, image: null },
  { id: "botoneras-63-horizontal-o-vertical-alfanumerico-auton", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL ALFANUMERICO AUTONOMO (c/accesorios)", group: null, image: null },
  { id: "botoneras-64-horizontal-o-vertical-2-con-gong", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL 2\" CON GONG", group: null, image: null },
  { id: "botoneras-65-horizontal-o-vertical-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-66-horizontal-o-vertical-lcd-grande-azul", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL LCD GRANDE AZUL", group: null, image: null },
  { id: "botoneras-67-horizontal-o-vertical-lcd-4-3", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL LCD 4,3\"", group: null, image: null },
  { id: "botoneras-68-horizontal-o-vertical-lcd-5-6", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL LCD 5,6\"", group: null, image: null },
  { id: "botoneras-69-horizontal-o-vertical-lcd-7", cat: "botoneras", catLabel: "Botoneras", name: "HORIZONTAL O VERTICAL LCD 7\"", group: null, image: null },
  { id: "botoneras-70-con-un-boton-m-m-1", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON M.M. 1\"", group: null, image: null },
  { id: "botoneras-71-con-un-boton-m-m-2", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON M.M. 2\"", group: null, image: null },
  { id: "botoneras-72-con-un-boton-m-m-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON M.M. 3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-73-con-un-boton-m-m-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON M.M. 3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-74-con-un-boton-m-m-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON M.M. ALFANUMERICO", group: null, image: null },
  { id: "botoneras-75-con-un-boton-m-m-alfanumerico-autonomo-c", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON M.M. ALFANUMERICO AUTONOMO (c/accesorios)", group: null, image: null },
  { id: "botoneras-76-con-un-boton-m-m-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON M.M. LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-77-con-un-boton-lcd-grande-azul", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON LCD GRANDE AZUL", group: null, image: null },
  { id: "botoneras-78-con-un-boton-lcd-4-3", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON LCD 4,3\"", group: null, image: null },
  { id: "botoneras-79-con-un-boton-lcd-5-6", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON LCD 5,6\"", group: null, image: null },
  { id: "botoneras-80-con-un-boton-lcd-7", cat: "botoneras", catLabel: "Botoneras", name: "CON UN BOTON LCD 7\"", group: null, image: null },
  { id: "botoneras-81-con-dos-botones-m-m-1", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES M.M.1\"", group: null, image: null },
  { id: "botoneras-82-con-dos-botones-m-m-2", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES M.M.2\"", group: null, image: null },
  { id: "botoneras-83-con-dos-botones-m-m-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES M.M.3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-84-con-dos-botones-m-m-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES M.M.3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-85-con-dos-botones-m-m-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES M.M. ALFANUMERICO", group: null, image: null },
  { id: "botoneras-86-con-dos-botones-m-m-alfanumerico-autonom", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES M.M. ALFANUMERICO AUTONOMO (c/accesorios)", group: null, image: null },
  { id: "botoneras-87-con-dos-botones-m-m-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES M.M. LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-88-con-dos-botones-lcd-grande-azul", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES LCD GRANDE AZUL", group: null, image: null },
  { id: "botoneras-89-con-dos-botones-lcd-4-3", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES LCD 4,3\"", group: null, image: null },
  { id: "botoneras-90-con-dos-botones-lcd-5-6", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES LCD 5,6\"", group: null, image: null },
  { id: "botoneras-91-con-dos-botones-lcd-7", cat: "botoneras", catLabel: "Botoneras", name: "CON DOS BOTONES LCD 7\"", group: null, image: null },
  { id: "botoneras-92-doble-con-un-boton-m-m-1", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON M.M.1\"", group: null, image: null },
  { id: "botoneras-93-doble-con-un-boton-m-m-2", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON M.M.2\"", group: null, image: null },
  { id: "botoneras-94-doble-con-un-boton-m-m-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON M.M.3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-95-doble-con-un-boton-m-m-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON M.M.3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-96-doble-con-un-boton-m-m-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON M.M. ALFANUMERICO", group: null, image: null },
  { id: "botoneras-97-doble-con-un-boton-m-m-alfanumerico-auto", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON M.M. ALFANUMERICO AUTONOMO (c/accesorios)", group: null, image: null },
  { id: "botoneras-98-doble-con-un-boton-m-m-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON M.M. LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-99-doble-con-un-boton-lcd-grande-azul", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON LCD GRANDE AZUL", group: null, image: null },
  { id: "botoneras-100-doble-con-un-boton-lcd-4-3", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON LCD 4,3\"", group: null, image: null },
  { id: "botoneras-101-doble-con-un-boton-lcd-5-6", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON LCD 5,6\"", group: null, image: null },
  { id: "botoneras-102-doble-con-un-boton-lcd-7", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON UN BOTON LCD 7\"", group: null, image: null },
  { id: "botoneras-103-doble-con-dos-botones-m-m-1", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES M.M.1\"", group: null, image: null },
  { id: "botoneras-104-doble-con-dos-botones-m-m-2", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES M.M.2\"", group: null, image: null },
  { id: "botoneras-105-doble-con-dos-botones-m-m-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES M.M.3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-106-doble-con-dos-botones-m-m-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES M.M.3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-107-doble-con-dos-botones-m-m-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES M.M. ALFANUMERICO", group: null, image: null },
  { id: "botoneras-108-doble-con-dos-botones-m-m-alfanumerico-a", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES M.M. ALFANUMERICO AUTONOMO (c/accesorios)", group: null, image: null },
  { id: "botoneras-109-doble-con-dos-botones-m-m-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES M.M. LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-110-doble-con-dos-botones-lcd-grande-azul", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES LCD GRANDE AZUL", group: null, image: null },
  { id: "botoneras-111-doble-con-dos-botones-lcd-4-3", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES LCD 4,3\"", group: null, image: null },
  { id: "botoneras-112-doble-con-dos-botones-lcd-5-6", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES LCD 5,6\"", group: null, image: null },
  { id: "botoneras-113-doble-con-dos-botones-lcd-7", cat: "botoneras", catLabel: "Botoneras", name: "DOBLE CON DOS BOTONES LCD 7\"", group: null, image: null },
  { id: "botoneras-114-linternas-bidireccionales", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNAS BIDIRECCIONALES", group: null, image: null },
  { id: "botoneras-115-linterna-doble", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA DOBLE", group: null, image: null },
  { id: "botoneras-116-linterna-doble-display-1", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA DOBLE DISPLAY 1\"", group: null, image: null },
  { id: "botoneras-117-linterna-doble-display-2", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA DOBLE DISPLAY 2\"", group: null, image: null },
  { id: "botoneras-118-linterna-con-indicador-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR 3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-119-linterna-con-indicador-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR 3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-120-linterna-con-indicador-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR ALFANUMERICO", group: null, image: null },
  { id: "botoneras-121-linterna-con-indicador-alfanumerico-auto", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR ALFANUMERICO AUTONOMO (c/accesorios)", group: null, image: null },
  { id: "botoneras-122-linterna-con-indicador-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-123-linterna-con-indicador-lcd-grande-azul", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD GRANDE AZUL", group: null, image: null },
  { id: "botoneras-124-linterna-con-indicador-lcd-4-3", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD 4,3\"", group: null, image: null },
  { id: "botoneras-125-linterna-con-indicador-lcd-5-6", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD 5,6\"", group: null, image: null },
  { id: "botoneras-126-linterna-con-indicador-lcd-7", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD 7\"", group: null, image: null },
  { id: "botoneras-127-linterna-con-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON GONG", group: null, image: null },
  { id: "botoneras-128-linterna-display-1-y-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA DISPLAY 1\" Y GONG", group: null, image: null },
  { id: "botoneras-129-linterna-display-2-y-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA DISPLAY 2\" Y GONG", group: null, image: null },
  { id: "botoneras-130-linterna-con-indicador-3-hilos-1-y-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR 3 HILOS 1\" Y GONG", group: null, image: null },
  { id: "botoneras-131-linterna-con-indicador-3-hilos-2-y-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR 3 HILOS 2\" Y GONG", group: null, image: null },
  { id: "botoneras-132-linterna-con-indicador-alfanumerico-y-go", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR ALFANUMERICO Y GONG", group: null, image: null },
  { id: "botoneras-133-linterna-con-indicador-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-134-linterna-con-indicador-lcd-chico-azul-y-", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD CHICO AZUL Y GONG", group: null, image: null },
  { id: "botoneras-135-linterna-con-indicador-lcd-4-3-y-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD 4,3\" Y GONG", group: null, image: null },
  { id: "botoneras-136-linterna-con-indicador-lcd-5-6-y-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD 5,6\" Y GONG", group: null, image: null },
  { id: "botoneras-137-linterna-con-indicador-lcd-7-y-gong", cat: "botoneras", catLabel: "Botoneras", name: "LINTERNA CON INDICADOR LCD 7\" Y GONG", group: null, image: null },
  { id: "botoneras-138-repuestos-de-indicadores", cat: "botoneras", catLabel: "Botoneras", name: "REPUESTOS DE INDICADORES", group: null, image: null },
  { id: "botoneras-139-accesorios-indicador-alfanumerico-autono", cat: "botoneras", catLabel: "Botoneras", name: "ACCESORIOS INDICADOR ALFANUMERICO AUTONOMO", group: null, image: null },
  { id: "botoneras-140-acrilico-suelto-60-x-90", cat: "botoneras", catLabel: "Botoneras", name: "ACRILICO SUELTO 60 X 90", group: null, image: null },
  { id: "botoneras-141-fuente-de-indicador-alfanumerico", cat: "botoneras", catLabel: "Botoneras", name: "FUENTE DE INDICADOR ALFANUMERICO", group: null, image: null },
  { id: "botoneras-142-tarjeta-de-indicador-1", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR 1\"", group: null, image: null },
  { id: "botoneras-143-tarjeta-de-indicador-2", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR 2\"", group: null, image: null },
  { id: "botoneras-144-tarjeta-de-indicador-3-hilos-1", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR 3 HILOS 1\"", group: null, image: null },
  { id: "botoneras-145-tarjeta-de-indicador-3-hilos-2", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR 3 HILOS 2\"", group: null, image: null },
  { id: "botoneras-146-tarjeta-de-indicador-alfanumerico-sin-fu", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR ALFANUMERICO (SIN FUENTE)", group: null, image: null },
  { id: "botoneras-147-tarjeta-de-indicador-alfa-autonomo-con-a", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR ALFA. AUTONOMO (con accesorios) hasta 10 paradas", group: null, image: null },
  { id: "botoneras-148-tarjeta-de-indicador-lcd-chico-azul", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR LCD CHICO AZUL", group: null, image: null },
  { id: "botoneras-149-tarjeta-de-indicador-lcd-grande-azul", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR LCD GRANDE AZUL", group: null, image: null },
  { id: "botoneras-150-tarjeta-de-indicador-lcd-4-3", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR LCD 4,3\"", group: null, image: null },
  { id: "botoneras-151-tarjeta-de-indicador-lcd-5-6", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR LCD 5,6\"", group: null, image: null },
  { id: "botoneras-152-tarjeta-de-indicador-lcd-7", cat: "botoneras", catLabel: "Botoneras", name: "TARJETA DE INDICADOR LCD 7\"", group: null, image: null },
  { id: "botoneras-153-ventana-con-acrilico", cat: "botoneras", catLabel: "Botoneras", name: "VENTANA CON ACRILICO", group: null, image: null },
  { id: "botoneras-154-ventana-con-crilico-doble-grabado", cat: "botoneras", catLabel: "Botoneras", name: "VENTANA CON CRILICO DOBLE GRABADO", group: null, image: null },
  { id: "contactoras-lg-1-gmc-9", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-9", group: null, image: null },
  { id: "contactoras-lg-2-gmc-12", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-12", group: null, image: null },
  { id: "contactoras-lg-3-gmc-18", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-18", group: null, image: null },
  { id: "contactoras-lg-4-gmc-22", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-22", group: null, image: null },
  { id: "contactoras-lg-5-gmc-32", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-32", group: null, image: null },
  { id: "contactoras-lg-6-gmc-40", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-40", group: null, image: null },
  { id: "contactoras-lg-7-gmc-50", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-50", group: null, image: null },
  { id: "contactoras-lg-8-gmc-65", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-65", group: null, image: null },
  { id: "contactoras-lg-9-gmc-85", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-85", group: null, image: null },
  { id: "contactoras-lg-10-gmc-100", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-100", group: null, image: null },
  { id: "contactoras-lg-11-gmc-125", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-125", group: null, image: null },
  { id: "contactoras-lg-12-gmc-150", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GMC-150", group: null, image: null },
  { id: "contactoras-lg-13-gtk-22-hasta-22-a-7-10-9-13-12-18", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GTK-22 HASTA 22 A 7/10 9/13 12/18", group: null, image: null },
  { id: "contactoras-lg-14-gtk-40-hasta-40-a", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GTK-40 HASTA 40 A", group: null, image: null },
  { id: "contactoras-lg-15-gtk-85-hasta-85-a", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GTK-85 HASTA 85 A", group: null, image: null },
  { id: "contactoras-lg-16-gtk-100-hasta-100-a", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GTK-100 HASTA 100 A", group: null, image: null },
  { id: "contactoras-lg-17-bloqueo-mecanico-p-gmc-9-85-ar9", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "BLOQUEO MECANICO P/GMC 9/85 AR9", group: null, image: null },
  { id: "contactoras-lg-18-c-aux-au4-2na-2nc-gmc-9-85", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "C.AUX.AU4 2NA + 2NC GMC 9-85", group: null, image: null },
  { id: "contactoras-lg-19-llave-yale", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "LLAVE YALE", group: null, image: null },
  { id: "contactoras-lg-20-guardamotor", cat: "contactoras-lg", catLabel: "Contactoras LG", name: "GUARDAMOTOR", group: null, image: null },
  { id: "controles-electromecanicos-1-automatico-1-velocidad-sin-aceleracion", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "AUTOMATICO 1 VELOCIDAD SIN ACELERACION", group: null, image: null },
  { id: "controles-electromecanicos-2-automatico-1-velocidad-con-aceleracion", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "AUTOMATICO 1 VELOCIDAD CON ACELERACION", group: null, image: null },
  { id: "controles-electromecanicos-3-automatico-2-velocidades", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "AUTOMATICO 2 VELOCIDADES", group: null, image: null },
  { id: "controles-electromecanicos-4-hidraulico", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "HIDRAULICO", group: null, image: null },
  { id: "controles-electromecanicos-5-llamada-registrada-1-velocidad", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "LLAMADA REGISTRADA 1 VELOCIDAD", group: null, image: null },
  { id: "controles-electromecanicos-6-llamada-registrada-2-velocidades", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "LLAMADA REGISTRADA 2 VELOCIDADES", group: null, image: null },
  { id: "controles-electromecanicos-7-colectivo-descendente-1-velocidad", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO DESCENDENTE 1 VELOCIDAD", group: null, image: null },
  { id: "controles-electromecanicos-8-colectivo-descendente-2-velocidades", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO DESCENDENTE 2 VELOCIDADES", group: null, image: null },
  { id: "controles-electromecanicos-9-colectivo-completo-1-velocidad", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO COMPLETO 1 VELOCIDAD", group: null, image: null },
  { id: "controles-electromecanicos-10-colectivo-completo-2-velocidades", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO COMPLETO 2 VELOCIDADES", group: null, image: null },
  { id: "controles-electromecanicos-11-colectivo-descendente-duplex-1-velocidad", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO DESCENDENTE DUPLEX 1 VELOCIDAD", group: null, image: null },
  { id: "controles-electromecanicos-12-colectivo-descendente-duplex-2-velocidad", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO DESCENDENTE DUPLEX 2 VELOCIDADES", group: null, image: null },
  { id: "controles-electromecanicos-13-colectivo-completo-duplex-1-velocidad", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO COMPLETO DUPLEX 1 VELOCIDAD", group: null, image: null },
  { id: "controles-electromecanicos-14-colectivo-completo-duplex-2-velocidades", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO COMPLETO DUPLEX 2 VELOCIDADES", group: null, image: null },
  { id: "controles-electromecanicos-15-puertas-automaticas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "PUERTAS AUTOMATICAS", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-16-con-y-sin-ascensorista", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "CON Y SIN ASCENSORISTA", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-17-potencial", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "POTENCIAL", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-18-segunda-aceleradora", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "SEGUNDA ACELERADORA", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-19-interconeccion-en-maniobra-colectiva", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "INTERCONECCION EN MANIOBRA COLECTIVA", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-20-palancas-semireforzadas-1-velocidad-13-a", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "PALANCAS SEMIREFORZADAS 1 VELOCIDAD 13 A 15 HP", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-21-palancas-semireforzadas-2-velocidades-13", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "PALANCAS SEMIREFORZADAS 2 VELOCIDADES 13 A 15 HP", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-22-palancas-superreforzadas-1-velocidad-16-", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "PALANCAS SUPERREFORZADAS 1 VELOCIDAD 16 HP EN ADEL.", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-23-palancas-superreforzadas-2-velocidades-1", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "PALANCAS SUPERREFORZADAS 2 VELOCIDADES 16 HP EN ADEL.", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-24-hidraulico-estrella-triangulo", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "HIDRAULICO ESTRELLA TRIANGULO", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-25-botones-de-nivelar", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "BOTONES DE NIVELAR", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-26-renivelacion-hidraulico", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "RENIVELACION HIDRAULICO", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-27-interferencia", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "INTERFERENCIA", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-28-arranque-directo-contactoras-gabinete", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "ARRANQUE DIRECTO (CONTACTORAS + GABINETE)", group: "Adicionales Electromecánicos", image: null },
  { id: "controles-electromecanicos-29-3-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "3 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-30-4-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "4 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-31-5-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "5 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-32-6-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "6 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-33-7-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "7 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-34-8-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "8 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-35-9-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "9 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-36-10-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "10 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-37-11-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "11 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-38-12-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "12 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-39-13-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "13 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-40-14-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "14 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-41-15-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "15 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-42-16-paradas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "16 PARADAS", group: "Selectores", image: null },
  { id: "controles-electromecanicos-43-colectivo-completo", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "COLECTIVO COMPLETO", group: "Adicional Selectores", image: null },
  { id: "controles-electromecanicos-44-puertas-automaticas", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "PUERTAS AUTOMATICAS", group: "Adicional Selectores", image: null },
  { id: "controles-electromecanicos-45-duplex", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "DUPLEX", group: "Adicional Selectores", image: null },
  { id: "controles-electromecanicos-46-finales", cat: "controles-electromecanicos", catLabel: "Controles Electromecánicos", name: "FINALES", group: "Adicional Selectores", image: null },
];

function maclarExtraImagePath(item) {
  return item.image ? `assets/img/productos-extra/${item.image}` : null;
}

